# Generated by Django 5.2.3 on 2025-06-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_approve_posts', 'Can approve posts')]},
        ),
    ]
