# Generated by Django 5.0.4 on 2024-07-01 19:01

from django.db import migrations


def rarity_ranking(apps, schema_editor):
    items = apps.get_model('main_app', 'Item')
    item = items.objects.all()

    for current_item in item:
        if current_item.price <= 10:
            current_item.rarity = "Rare"
        elif current_item.price <= 20:
            current_item.rarity = "Very Rare"
        elif current_item.price <= 30:
            current_item.rarity = "Extremely Rare"
        else:
            "Mega Rare"

    items.objects.bulk_update(item, ['rarity'])


def set_rarity_ranking_default(apps, schema_editor):
    items = apps.get_model('main_app', 'Item')

    for item in items.objects.all():
        item.rarity = items._meta.get_field('rarity').default


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(rarity_ranking, set_rarity_ranking_default)
    ]
