# Generated by Django 5.0.4 on 2024-07-03 17:51

from django.db import migrations


def set_new_price(apps, schema_editor):



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_migrate_price_rarity'),
    ]

    operations = [
    ]
